kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.9-jdk21-jammy
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - gradle test --no-daemon

  - name: publish
    image: gradle:8.9-jdk21-jammy
    volumes:
      - name: build-output
        path: /tmp/build/
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - gradle --no-daemon --build-cache jlinkTar publish
      - cp ./build/minimum-effort-search.tgz /tmp/build/minimum-effort-search.tgz
    when:
      event: tag

  - name: release
    image: plugins/github-release
    volumes:
      - name: build-output
        path: /tmp/build/
    settings:
      api_key:
        from_secret: GH_TOKEN
      files: /tmp/build/minimum-effort-search.tgz
    when:
      event: tag

volumes:
  - name: build-output
    temp: {}
