kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.1.1-jdk17-jammy
    commands:
      - gradle test

  - name: publish
    image: gradle:8.1.1-jdk17-jammy
    volumes:
      - name: build-output
        path: /tmp/build/jar/
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - apt-get update && apt-get install -y curl
      - gradle execJar publish
      - cp ./build/libs/* /tmp/build/jar/
    when:
      event: tag

  - name: release
    image: plugins/github-release
    volumes:
      - name: build-output
        path: /tmp/build/jar/
    settings:
      api_key:
        from_secret: GH_TOKEN
      files: /tmp/build/jar/*
    when:
      event: tag

volumes:
  - name: build-output
    temp: {}
